//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolUP.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Country_Valitov
    {
        public int id { get; set; }
        public string name { get; set; }
        public string stolica { get; set; }
        public string kontinent { get; set; }
        public Nullable<int> naselenie { get; set; }
        public Nullable<int> ploshad { get; set; }
        public Nullable<int> tip { get; set; }
    }
}
