//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolUP.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exam
    {
        public int id { get; set; }
        public string date { get; set; }
        public Nullable<int> kod { get; set; }
        public Nullable<int> reg_nomer { get; set; }
        public Nullable<int> tab_nomer { get; set; }
        public string auditorya { get; set; }
        public Nullable<int> ocenka { get; set; }
    
        public virtual Disciplina Disciplina { get; set; }
        public virtual Sotrudnik Sotrudnik { get; set; }
        public virtual Student Student { get; set; }
    }
}
