//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolUP.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Гимназисты
    {
        public int ID { get; set; }
        public string fname { get; set; }
        public string @object { get; set; }
        public string school { get; set; }
        public Nullable<double> marks { get; set; }
    }
}
